# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  - trigger: ":joy1"
    replace: "(⁀ᗢ⁀)"

  - trigger: ":joy2"
    replace: "٩(◕‿◕｡)۶"

  - trigger: ":joy3"
    replace: "(＾▽＾)"

  - trigger: ":joy4"
    replace: "(◠‿◠)"

  - trigger: ":love1"
    replace: "ヽ(♡‿♡)ノ"

  - trigger: ":love2"
    replace: "(❤ω❤)"

  - trigger: ":love3"
    replace: "╰(*´︶`*)╯♡"

  - trigger: ":love4"
    replace: "(´♡‿♡`)"

  - trigger: ":love5"
    replace: "(◕‿◕)♡"

  - trigger: ":love6"
    replace: "( ´ ∀ `)ノ～ ♡"

  - trigger: ":love7"
    replace: "♡＼(￣▽￣)／♡"

  - trigger: ":kiss"
    replace: "(っ˘з(˘⌣˘ ) ♡"

  - trigger: ":embarrassment1"
    replace: "(⁄ ⁄•⁄ω⁄•⁄ ⁄)"

  - trigger: ":embarrassment2"
    replace: "(⁄ ⁄>⁄ ▽ ⁄<⁄ ⁄)"

  - trigger: ":embarrassment3"
    replace: "(*μ_μ)"

  - trigger: ":ohstopit"
    replace: "(ง ื▿ ื)ว"

  - trigger: ":sympathy"
    replace: "(っ´ω`)ﾉ(╥ω╥)"

  - trigger: ":angry"
    replace: "(」°ロ°)」"

  - trigger: ":fuckyou1"
    replace: "凸(￣ヘ￣)"

  - trigger: ":fuckyou2"
    replace: "凸( ` ﾛ ´ )凸"

  - trigger: ":furious"
    replace: "(ノ°益°)ノ"

  - trigger: ":sad1"
    replace: "(╯_╰)"

  - trigger: ":sad2"
    replace: "(╯︵╰,)"

  - trigger: ":sad3"
    replace: "(｡•́︿•̀｡)"

  - trigger: ":dead"
    replace: "(×_×)"

  - trigger: ":eshrug"
    replace: "¯\_(ツ)_/¯"

  - trigger: ":shrug"
    replace: "¯\\_(ツ)_/¯"

  - trigger: ":meh"
    replace: "┐( ˘､˘ )┌	"

  - trigger: ":wat1"
    replace: "(•ิ_•ิ)?"

  - trigger: ":wat2"
    replace: "(・・ ) ?"

  - trigger: ":shock"
    replace: "(o_O)"

  - trigger: ":shock1"
    replace: ""

  - trigger: ":hi1"
    replace: "(°▽°)/"

  - trigger: ":hi2"
    replace: "(￣▽￣)ノ"

  - trigger: ":wink"
    replace: "( ﾟｏ⌒)"

  - trigger: ":sorry"
    replace: "(シ. .)シ"

  - trigger: ":run1"
    replace: "C= C= C= C=┌( `ー´)┘"

  - trigger: ":run2"
    replace: "C= C= C= C= C=┌(;・ω・)┘"

  - trigger: ":sleep1"
    replace: "(－_－) zzZ"

  - trigger: ":sleep2"
    replace: "(￣o￣) zzZZzzZZ"

  - trigger: ":bear1"
    replace: "ʕ •ᴥ• ʔ"

  - trigger: ":bear2"
    replace: "ʕ ᵔᴥᵔ ʔ"

  - trigger: ":lenny"
    replace: "( ͡° ͜ʖ ͡°)"

  - trigger: ":sadlenny"
    replace: "( ͡° ʖ̯ ͡°)"

  - trigger: ":angrylenny"
    replace: "( ͠° ͟ʖ ͡°)"

  - trigger: ":disgusted"
    replace: "( ಠ ʖ̯ ಠ)"

  - trigger: ":tableflip"
    replace: "( ╯°□°)╯ ┻━━┻	"

  - trigger: ":tableback"
    replace: "┬─┬ノ( º _ ºノ)"

  - trigger: ":ghost"
    replace: "ᶘᵒᴥᵒᶅ"

  - trigger: ":cute"
    replace: "(｡◕‿‿◕｡)"

  - trigger: ":excited"
    replace: "(ʘ‿ʘ)"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"
