#! /bin/sh
export gap=10
export PANEL_HEIGHT=25

## Colors, gaps
#[[ -f "${HOME}/.cache/wal/colors.sh" ]] || setbg
. "${HOME}/.cache/wal/colors.sh"

bspc config window_gap $gap;
bspc config top_padding $(($PANEL_HEIGHT+$gap))
bspc config left_padding $(($gap / 5))
bspc config right_padding $(($gap / 5))
bspc config bottom_padding $(($gap / 2))
bspc config split_ratio         0.52

bspc config border_width 3
bspc config normal_border_color "$color0"
bspc config active_border_color "$color0"
#bspc config focused_border_color "$color13"
bspc config focused_border_color "$color4"
bspc config presel_feedback_color "$color1"

## Various settings
bspc config gapless_monocle false
bspc config borderless_monocle false
bspc config single_monocle true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
## Honor size hints: do not make windows smaller than they wish to be
#bspc config honor_size_hints true

# Use mouse to change focus
bspc config focus_follows_pointer false

#bspc monitor -d web code term social movie music prn "=)"
#bspc monitor DP-1 -d 1 2 3 4 5
#bspc monitor HDMI-2 -d 6 7 8 9
#workspaces_multimonitor &
bspc monitor -d 1 2 3 4 5 6 7 8 9 "=)"

bspc rule -a screenkey --unmanage
bspc rule -a spotify state=pseudo_tiled
bspc rule -a skype state=pseudo_tiled
bspc rule -a transmission-gtk state=pseudo_tiled
#bspc rule -a "microsoft teams - preview" desktop=social
bspc rule -a wpa_gui state=pseudo_tiled
bspc rule -a libreoffice state=tiled
bspc rule -a '*:libreofficedev' state=tiled
bspc rule -a '*:soffice' state=tiled
bspc rule -a 'Zathura' state=tiled

xset r rate 170 60 &	# Speed xrate up
setxkbmap pl &
setxkbmap -option caps:swapescape

## Autostart apps
#pidswallow --loop &
launch_polybar --silent &

#sxhkd &
#. $HOME/.config/bspwm/autostart
