#!/bin/zsh

source "${HOME}/.cache/wal/colors.sh"

mkdir -p  "${HOME}/.config/dunst"
mkdir -p  "${HOME}/.config/zathura"
ln -sf    "${HOME}/.cache/wal/dunstrc"    "${HOME}/.config/dunst/dunstrc"
ln -sf    "${HOME}/.cache/wal/zathurarc"    "${HOME}/.config/zathura/zathurarc"

xrdb -merge ~/.cache/wal/colors.Xresources &
#sh ~/.config/bspwm/bspwmrc &

pkill dunst; dunst &
